app:
  user_models:
    name_maximum: 50
    email_maximum: 255
    password_minimum: 6
    time_expired: 2
  yes_remember_me: "1"
  users_helper:
    size: 80
  micropost_models:
    content_maximum: 140
    picture_size: 5
  gravatar_for:
    size: 50
  per_page: 10
config:
  production:
    host: "<your heroku app>.herokuapp.com"
    address: "smtp.sendgrid.net"
    port: "587"
    user_name: "SENDGRID_USERNAME"
    password: "SENDGRID_PASSWORD"
    domain: "heroku.com"
