app:
  user_models:
    name_maximum: 50
    email_maximum: 255
    password_minimum: 6
    time_expired: 2
  yes_remember_me: "1"
  users_helper:
    size: 80
  micropost_models:
    content_maximum: 140
    picture_size: 5
  gravatar_for:
    size: 50
    size_30: 30
  per_page: 10
config:
  production:
    host: "linhnv-sample-app.herokuapp.com"
    address: "smtp.gmail.com"
    port: "587"
    user_name: "dragonballlegend0111@gmail.com"
    password: "son_goku"
